version: '2'
services:
  db:
    image: "postgres:12"
    environment:
      POSTGRES_DB: ENV[DATABASE_NAME]
      POSTGRES_PASSWORD: ENV[DATABASE_PASSWORD]
      POSTGRES_USER: ENV[DATABASE_USER]
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=db
      - PGUSER=manjinder98
    volumes:
      - .:/demo_blog
    ports:
      - "3000:3000"
    depends_on:
      - db