default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  username: manjinder98
  password: 7x!27DZKv1Q%
  timeout: 5000

development:
  <<: *default
  database: demo_blog_development

test:
  <<: *default
  database: demo_blog_test